version: '3.7'

services:
    cosignerpool:
        build:
            context: ../
            dockerfile: $PWD/Cosignerpool/Dockerfile
        network_mode: host
        ports:
            - "${COSIGNER_SERVICE_PORT}:8080"
        volumes:
            - "/db_cosigner:/db_cosigner"
            - "/var/log/cosignerpool/:/app/src/log"
        depends_on:
            - nginxSSL
    nginx:
        image: nginx:latest
        network_mode: host
        ports:
            - "80:80"
        volumes:
            - "./Nginx/Cosignerpool.template:/etc/nginx/conf.d/Cosignerpool.template"
        command: /bin/bash -c "cat /etc/nginx/conf.d/Cosignerpool.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        depends_on:
            - nginxSSL
    nginxSSL:
        image: nginx:latest
        network_mode: host
        ports:
            - "443:443"
        volumes:
            - "./Nginx/entrypoint.sh:/app/entrypoint.sh"
            - "./Nginx/CosignerpoolSSL.template:/etc/nginx/conf.d/CosignerpoolSSL.template"
            - "/var/log/nginx/:/var/log/nginx/"
            - "openssl-etc:/etc/certs"
        environment:
            - NGINX_HOST=${serverName}
        restart: always
        depends_on:
            - openssl 
        command: /bin/sh -c /app/entrypoint.sh
    openssl:
        build:
            context: $PWD/OpenSSL
            dockerfile: $PWD/OpenSSL/Dockerfile
        volumes:
            - "./OpenSSL/entrypoint.sh:/app/entrypoint.sh"
            - "openssl-etc:/etc/certs"
        entrypoint: /bin/sh -c /app/entrypoint.sh
volumes:
        openssl-etc:

